project:
  type: website
  output-dir: docs
  
# ~~ leave the other parts of the file as they are for now ~~

website:
  title: "Jared Umphress"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd
      - interests.qmd
      - surf.qmd

format:
  html:
    theme: styles.scss
    mainfont: EB Garamond
    css: styles.scss
    toc: true
    page-layout: full
    include-after-body:
      - text: |
          <script>
          document.querySelectorAll('script[src*="polyfill.io"]').forEach(s => s.remove());
          </script>

